
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";



const roboto = Roboto({ subsets: ["latin"], weight: ['500'] });

export const metadata: Metadata = {
  title: "Petro Track",
  description: "Generated by create next app",
};

export default function RootLayout({

  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: { path: string }
}>) {
  const { path } = params
  return (
    <html lang="en">

      <body className={roboto.className}>
        <Header />
        {children}
        {/* <Footer /> */}

      </body>

    </html>
  );
}
